# Generated by Django 3.0.1 on 2019-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191227_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
