# Generated by Django 3.0.1 on 2019-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='homework_images')),
                ('description', models.TextField()),
            ],
        ),
    ]
