# Generated by Django 3.0.1 on 2019-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
        migrations.AddField(
            model_name='homework',
            name='theme',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
