# Generated by Django 3.0.1 on 2020-01-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20191230_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='theme',
        ),
    ]
