# Generated by Django 3.0.1 on 2020-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_homework_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
