# Generated by Django 3.0.1 on 2020-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('theme', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_images/')),
                ('description', models.TextField(blank=True, default='')),
                ('fileSolution', models.FileField(blank=True, upload_to='school_materials/')),
                ('slug', models.SlugField(default='', max_length=250)),
                ('image_solution', models.ImageField(blank=True, null=True, upload_to='school_images/')),
                ('video_source', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
