# Generated by Django 3.0.1 on 2019-12-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_literature_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='book',
            new_name='books',
        ),
    ]
