# Generated by Django 3.0.1 on 2019-12-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_auto_20191229_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='books',
        ),
        migrations.AlterField(
            model_name='literature',
            name='image',
            field=models.ImageField(null=True, upload_to='literature_images'),
        ),
    ]
