# Generated by Django 3.0.1 on 2020-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_auto_20191230_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='literature_images'),
        ),
    ]
