# Generated by Django 3.0.1 on 2020-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathpage',
            name='solution',
        ),
        migrations.AddField(
            model_name='mathpage',
            name='fileSolution',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
