# Generated by Django 3.0.1 on 2019-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathpage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
