# Generated by Django 3.0.1 on 2020-01-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0002_mathpage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathpage',
            name='little_summary',
        ),
        migrations.AddField(
            model_name='mathpage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mathpage',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
