# Generated by Django 3.0.1 on 2020-01-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0004_auto_20200106_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathpage',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
