# Generated by Django 3.0.1 on 2020-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0005_mathpage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathpage',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, null=True)),
        ),
    ]
