# Generated by Django 3.0.1 on 2020-01-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0006_mathpage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathpage',
            name='slug',
        ),
    ]
