# Generated by Django 3.0.1 on 2020-01-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0008_auto_20200112_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathpage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='math_images/'),
        ),
        migrations.AlterField(
            model_name='mathpage',
            name='image_solution',
            field=models.ImageField(blank=True, default=None, upload_to='math_images/'),
        ),
        migrations.AlterField(
            model_name='mathpage',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mathpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
