# Generated by Django 3.0.1 on 2020-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0012_auto_20200112_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathpage',
            name='image_solution',
            field=models.ImageField(blank=True, default=None, upload_to='math_images/'),
        ),
    ]
