# Generated by Django 3.0.1 on 2020-01-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0013_auto_20200112_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathpage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='math_images/'),
        ),
        migrations.AlterField(
            model_name='mathpage',
            name='image_solution',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='math_images/'),
        ),
    ]
