# Generated by Django 3.0.1 on 2020-01-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0014_auto_20200130_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='math_images/'),
        ),
        migrations.AlterField(
            model_name='mathpage',
            name='image_solution',
            field=models.ImageField(blank=True, null=True, upload_to='math_images/'),
        ),
    ]
