# Generated by Django 3.0.1 on 2020-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0015_auto_20200130_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathpage',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
