# Generated by Django 3.0.1 on 2020-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathpage', '0016_mathpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathpage',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
