# Generated by Django 3.0.1 on 2020-08-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodpage',
            name='description',
            field=models.ImageField(blank=True, null=True, upload_to='metod_images/'),
        ),
    ]
